version: '3'

x-spark-common: &spark-common
  image: bitnami/spark:latest
  # build:
  #   context: .
  #   dockerfile: ./Dockerfile-spark
  volumes:
    - ./jobs:/opt/bitnami/spark/jobs
  networks:
    - sparking-flow
  environment:
    - PYSPARK_PYTHON=/usr/bin/python3.12
    - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.12

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: ./Dockerfile
  env_file:
    - airflow.env
  volumes:
    - ./jobs:/opt/airflow/jobs
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
  depends_on:
    - postgres
  networks:
    - sparking-flow

services:
  spark-master:
    <<: *spark-common
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "9090:8080"
      - "7077:7077"
    environment:
      SPARK_HOME: /opt/bitnami/spark
      JAVA_HOME: /opt/bitnami/java


  spark-worker:
    <<: *spark-common
    command: /opt/bitnami/spark/bin/spark-class org.apache.spark.deploy.worker.Worker  spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_CORE: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_MASTER_URL: spark://spark-master:7077

  postgres:
    image: postgres:14.0
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    networks:
      - sparking-flow

  scheduler:
    <<: *airflow-common
    command: >
      bash  -c "airflow db migrate && 
      airflow users create --username thierros --firstname thierry --lastname zoma --role Admin --email thierros2000@gmail.com --password admin && 
      airflow scheduler"

  web-server:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - scheduler

networks:
  sparking-flow:
  